// <auto-generated />
namespace MEAS.Data.SqlClient.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fkg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fkg));
        
        string IMigrationMetadata.Id
        {
            get { return "201709261307336_fkg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
